### ISSUE TITLE
MessageListActivity crashes due to glide

### ISSUE THREAD

**Issue by ravi-321** [chat21/chat21-android-sdk#49]
`java.lang.NoSuchMethodError: No virtual method load(Ljava/lang/String;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/~~4-U9kV6bteP12f1IemqMUg==/com.mykingdom.pricewars-L2AZ6S2mOT58FNIfV5Tn-Q==/base.apk)
        at org.chat21.android.ui.messages.activities.MessageListActivity.setPicture(MessageListActivity.java:406)
        at org.chat21.android.ui.messages.activities.MessageListActivity.initDirectToolbar(MessageListActivity.java:358)
        at org.chat21.android.ui.messages.activities.MessageListActivity.onCreate(MessageListActivity.java:209)
        at android.app.Activity.performCreate(Activity.java:7989)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3316)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3485)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)`

Dependencies:
//chat
    implementation 'org.chat21.android:chat21:1.0.10'
    implementation 'com.vanniktech:emoji-ios:0.5.1'
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    kapt 'com.github.bumptech.glide:compiler:4.11.0'

**Comment by gigincg** [comment]
Hey! 
 Were you able to solve this issue? I'm blocked with the same issue!

**Comment by gigincg** [comment]
In case you haven't solved this yet, if you revert back to Glide 3.7, This issue will resolve. Chat21 was built for the older version of Glide
